name: Deploy to Live Server

# Trigger the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH key to access the server
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 89.168.107.188 >> ~/.ssh/known_hosts

    # Upload the code to the live server via SSH
    - name: Deploy to Server
      run: |
        # Using -T to avoid allocating a pseudo-terminal
        ssh -T -o StrictHostKeyChecking=no ubuntu@89.168.107.188 << 'EOF'
          cd /websites/liotom
          git pull origin main  # Pull the latest changes
        EOF
