name: Pull Latest Code

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H 89.168.107.188 >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@89.168.107.188 "echo 'SSH Connection Successful'"

    - name: Deploy Latest Code
      run: |
        ssh -v -o StrictHostKeyChecking=no ubuntu@89.168.107.188 << 'EOF'
          cd /var/www/websites/liotom || exit 1
          git pull origin main || echo "Error in git pull"
        EOF
